using Mirror;
using UnityEngine;

namespace Game.Ship
{
    /// <summary>
    /// Server-authoritative free-moving ship. A genuine dynamic Rigidbody — collisions with rocks
    /// and docks produce real momentum, glancing bounces, and spin — but constrained to the water
    /// plane (Y position and pitch/roll frozen), so there is no buoyancy simulation to destabilise
    /// the deck or the players standing on it.
    ///
    /// Motion model, applied by the server each physics step:
    ///  - Thrust along the bow, scaled by the current sail level.
    ///  - Rudder torque around yaw, scaled by speed through the water (no steerage way when
    ///    stopped; reversing inverts the helm like a real boat).
    ///  - Anisotropic water drag: much higher sideways than forward, so hard turns drift.
    ///  - A dropped anchor multiplies drag and kills thrust — the emergency brake.
    ///
    /// Clients see the ship via the NetworkTransform on this object; their Rigidbody is kinematic.
    /// Sail level / rudder / anchor are SyncVars so stations and visuals read them anywhere.
    /// </summary>
    [RequireComponent(typeof(Rigidbody))]
    public class ShipController : NetworkBehaviour
    {
        [Header("Sails")]
        [Tooltip("Forward acceleration (m/s²) indexed by how many masts are unfurled; element 0 " +
                 "is all-furled. Generated by the builder from the mast count.")]
        [SerializeField] private float[] sailThrust = { 0f, 3f };
        [Tooltip("This ship's per-mast sail stations (wired by the builder). Speed = how many are unfurled.")]
        [SerializeField] private ShipSailStation[] sailStations = { };

        [Header("Steering")]
        [Tooltip("Yaw acceleration (deg/s²) at full rudder and full steerage speed.")]
        [SerializeField] private float rudderTurnAccel = 14f;
        [Tooltip("Speed through the water (m/s) at which the rudder reaches full authority.")]
        [SerializeField] private float steerageSpeed = 3f;

        [Header("Water")]
        [Tooltip("Drag on forward motion (fraction of velocity shed per second).")]
        [SerializeField] private float forwardDrag = 0.25f;
        [Tooltip("Drag on sideways motion. Keep well above forward drag so the ship carves, not slides.")]
        [SerializeField] private float lateralDrag = 1.6f;
        [Tooltip("Drag on yaw rotation.")]
        [SerializeField] private float yawDrag = 0.7f;

        [Header("Anchor")]
        [Tooltip("Extra drag on everything while the anchor is down.")]
        [SerializeField] private float anchorDrag = 3f;
        [Tooltip("How long hauling the anchor back up takes (s). Dropping is instant — the " +
                 "panic brake — but weighing is slow manual work at the bow.")]
        [SerializeField] private float weighSeconds = 5f;

        // Helm state, synced so every client can drive visuals (wheel spin) locally. Sail state
        // lives in the per-mast ShipSailStation SyncVars.
        [SyncVar] private float _rudder;                          // -1..1
        [SyncVar] private bool _anchored;
        [SyncVar] private bool _weighing; // anchor coming up; still holds until fully aweigh

        /// <summary>Current rudder deflection, -1 (hard port) to 1 (hard starboard).</summary>
        public float Rudder => _rudder;

        /// <summary>How many masts currently fly their sails. Valid on server and clients.</summary>
        public int SailLevel
        {
            get
            {
                int n = 0;
                foreach (ShipSailStation s in sailStations)
                    if (s != null && s.Unfurled) n++;
                return n;
            }
        }

        public int MaxSailLevel => sailStations.Length;
        public bool Anchored => _anchored;
        /// <summary>The anchor is being hauled in (still holding until it's fully up).</summary>
        public bool WeighingAnchor => _weighing;
        /// <summary>Signed speed along the bow in m/s. Only meaningful on the server.</summary>
        public float ForwardSpeed => Vector3.Dot(_rb.linearVelocity, transform.forward);
        /// <summary>Speed over the water in m/s regardless of heading. Only meaningful on the server.</summary>
        public float LinearSpeed => _rb.linearVelocity.magnitude;

        [Tooltip("How quickly the hull's height chases the wave surface (1/s). Low = a heavy " +
                 "hull that shoulders through chop; the swell still carries it up and over.")]
        [SerializeField] private float heaveResponse = 2.5f;

        private Rigidbody _rb;
        private float _weighDoneAt;       // server: when the running haul brings the anchor up
        [SyncVar] private float _planeY;  // the calm-water baseline the heave oscillates around
        private bool _warnedPlanarDrift;  // server: log the first correction so drift causes surface
        private Game.Gameplay.WaterSurface _water;
        private float _nextWaterScan;

        /// <summary>How far the hull currently rides above its calm-water baseline. Valid on
        /// every peer (the baseline is synced; the height comes off the replicated transform).
        /// Visual layers subtract this so they only add what the physics hasn't already done.</summary>
        public float HeaveOffset => transform.position.y - _planeY;

        private void Awake()
        {
            _rb = GetComponent<Rigidbody>();
            // Planar constraint on rotation only: X/Z translation and yaw are free, and the
            // hull's HEIGHT is driven onto the wave field each step — the ship really rides
            // the sea. Tilt stays visual (ShipFloatView) so the walkable colliders and
            // everything networked keep a level deck.
            _rb.constraints = RigidbodyConstraints.FreezeRotationX
                            | RigidbodyConstraints.FreezeRotationZ;
            _rb.useGravity = false;
            _rb.linearDamping = 0f;   // drag is modelled explicitly, per-axis, in FixedUpdate
            _rb.angularDamping = 0f;
            _rb.interpolation = RigidbodyInterpolation.Interpolate;
            IgnoreOwnKinematicColliders();
        }

        // The walkable colliders (deck, rails, masts, props) sit on kinematic CHILD bodies so
        // that player contacts can't shove the hull. Those children overlap the root's own hull
        // box by construction — silence the pairs so the ship doesn't fight itself.
        private void IgnoreOwnKinematicColliders()
        {
            Collider[] all = GetComponentsInChildren<Collider>(true);
            foreach (Collider a in all)
            {
                if (a.isTrigger || !a.enabled || !a.gameObject.activeInHierarchy) continue;
                if (a.attachedRigidbody != _rb) continue;
                foreach (Collider b in all)
                {
                    if (b.isTrigger || !b.enabled || !b.gameObject.activeInHierarchy) continue;
                    Rigidbody rb = b.attachedRigidbody;
                    if (rb != null && rb != _rb && rb.isKinematic)
                        Physics.IgnoreCollision(a, b, true);
                }
            }
        }

        public override void OnStartServer() => _planeY = transform.position.y;

        public override void OnStartClient()
        {
            // Remote ships are driven by the NetworkTransform, not local physics.
            if (!isServer) _rb.isKinematic = true;
        }

        [Server] public void SetRudder(float value) => _rudder = Mathf.Clamp(value, -1f, 1f);

        [Server]
        public void SetAnchored(bool anchored)
        {
            _anchored = anchored;
            _weighing = false; // any hard state change ends a haul in progress
        }

        /// <summary>Server: the bow anchor station's toggle. Dropping is instant anywhere —
        /// the panic brake. Weighing is slow manual work: the haul runs for weighSeconds
        /// (pressing again lets the anchor go back down) and the ship stays held until the
        /// anchor is fully up. When a jetty holds the ship it's the mooring line, not the
        /// anchor — release through the jetty (marked manually cast off, so the berth
        /// doesn't instantly re-catch), which is immediate.</summary>
        [Server]
        public void ServerToggleAnchor()
        {
            if (!_anchored)
            {
                SetAnchored(true);
                return;
            }
            foreach (DockMooring dock in FindObjectsByType<DockMooring>(FindObjectsSortMode.None))
                if (dock.MooredShip == this)
                {
                    dock.ServerCastOff();
                    return;
                }
            if (_weighing) _weighing = false; // let go again mid-haul
            else
            {
                _weighing = true;
                _weighDoneAt = Time.time + weighSeconds;
            }
        }

        [ServerCallback]
        private void FixedUpdate()
        {
            // A finished haul frees the ship. (Sails do NOT weigh a dropped anchor — that
            // is deliberate manual work at the bow; only a jetty's mooring line slips by
            // itself when the crew makes sail, handled by DockMooring.)
            if (_anchored && _weighing && Time.time >= _weighDoneAt) SetAnchored(false);

            Vector3 v = _rb.linearVelocity;
            float fwdSpeed = Vector3.Dot(v, transform.forward);

            // Thrust from however many masts fly canvas (the anchor holds the ship regardless).
            if (!_anchored)
            {
                float thrust = sailThrust[Mathf.Clamp(SailLevel, 0, sailThrust.Length - 1)];
                _rb.AddForce(transform.forward * thrust, ForceMode.Acceleration);
            }

            // Rudder authority builds with speed through the water and flips when making sternway.
            float authority = Mathf.Clamp01(Mathf.Abs(fwdSpeed) / Mathf.Max(0.01f, steerageSpeed));
            float sign = fwdSpeed >= 0f ? 1f : -1f;
            _rb.AddTorque(0f, _rudder * rudderTurnAccel * Mathf.Deg2Rad * authority * sign,
                0f, ForceMode.Acceleration);

            // Anisotropic water drag, plus the anchor's contribution on every axis.
            Vector3 fwd = transform.forward * fwdSpeed;
            Vector3 lat = v - fwd;
            float extra = _anchored ? anchorDrag : 0f;
            _rb.AddForce(-fwd * (forwardDrag + extra) - lat * (lateralDrag + extra),
                ForceMode.Acceleration);
            _rb.AddTorque(-_rb.angularVelocity * (yawDrag + extra), ForceMode.Acceleration);

            DriveHeave(v);
            EnforceLevel();
        }

        // Buoyant heave: chase the wave field's height under the hull (sampled at a few
        // stations and averaged, so chop shorter than the ship cancels out) with a lagged
        // vertical velocity — the swell carries the whole PHYSICAL ship, colliders, crew
        // and all, up and over. Everyone aboard rides for free via parenting, exactly as
        // they already do for the ship's planar motion; the synced wave clock keeps every
        // peer's sea agreeing with where the server put the hull.
        [Server]
        private void DriveHeave(Vector3 velocity)
        {
            if (_water == null && Time.time >= _nextWaterScan)
            {
                _nextWaterScan = Time.time + 2f;
                _water = FindAnyObjectByType<Game.Gameplay.WaterSurface>();
            }

            float targetY = _planeY;
            if (_water != null)
            {
                Vector3 fwd10 = transform.forward * 10f;
                Vector3 p = _rb.position;
                float mean = 0.25f * (
                    _water.HeightAt(p.x + fwd10.x, p.z + fwd10.z) +
                    _water.HeightAt(p.x - fwd10.x, p.z - fwd10.z) +
                    _water.HeightAt(p.x + transform.right.x * 3f, p.z + transform.right.z * 3f) +
                    _water.HeightAt(p.x - transform.right.x * 3f, p.z - transform.right.z * 3f));
                targetY += mean - _water.SurfaceY;
            }
            _rb.linearVelocity = new Vector3(velocity.x,
                (targetY - _rb.position.y) * heaveResponse, velocity.z);
        }

        // Level lock, belt-and-braces on top of the Rigidbody constraints: whatever manages
        // to pitch or roll the hull (a collider glitch, an unexpected torque path), flatten
        // it back to yaw-only before anyone can see it, and surface the first occurrence in
        // the log so the cause can be chased. Heave is legitimate now — the waves own it.
        [Server]
        private void EnforceLevel()
        {
            Vector3 e = _rb.rotation.eulerAngles;
            bool tilted = Mathf.Abs(Mathf.DeltaAngle(0f, e.x)) > 0.05f
                       || Mathf.Abs(Mathf.DeltaAngle(0f, e.z)) > 0.05f;
            if (!tilted) return;

            _rb.rotation = Quaternion.Euler(0f, e.y, 0f);
            Vector3 av = _rb.angularVelocity;
            _rb.angularVelocity = new Vector3(0f, av.y, 0f);

            if (!_warnedPlanarDrift)
            {
                _warnedPlanarDrift = true;
                Debug.LogWarning("[ShipController] Corrected off-level drift (tilt). " +
                                 "Something is fighting the rotation constraints — check for stray colliders/forces.", this);
            }
        }

    }
}
