using Mirror;
using UnityEngine;

namespace Game.Ship
{
    /// <summary>
    /// Server-authoritative free-moving ship. A genuine dynamic Rigidbody with NO rotation
    /// constraints — collisions with rocks and docks produce real momentum, glancing bounces
    /// and spin, the swell drives real heave (DriveHeave) and REAL pitch/roll (DriveTilt,
    /// through angular velocity, never a rotation teleport), so the deck everyone stands on
    /// genuinely tilts.
    ///
    /// Motion model, applied by the server each physics step:
    ///  - Thrust along the bow, scaled by the current sail level.
    ///  - Rudder torque around yaw, scaled by speed through the water (no steerage way when
    ///    stopped; reversing inverts the helm like a real boat).
    ///  - Anisotropic water drag: much higher sideways than forward, so hard turns drift.
    ///  - A dropped anchor multiplies drag and kills thrust — the emergency brake.
    ///
    /// Clients see the ship via the NetworkTransform on this object; their Rigidbody is kinematic.
    /// Sail level / rudder / anchor are SyncVars so stations and visuals read them anywhere.
    /// </summary>
    [RequireComponent(typeof(Rigidbody))]
    public class ShipController : NetworkBehaviour
    {
        [Header("Sails")]
        [Tooltip("Forward acceleration (m/s²) indexed by how many masts are unfurled; element 0 " +
                 "is all-furled. Generated by the builder from the mast count.")]
        [SerializeField] private float[] sailThrust = { 0f, 3f };
        [Tooltip("This ship's per-mast sail stations (wired by the builder). Speed = how many are unfurled.")]
        [SerializeField] private ShipSailStation[] sailStations = { };

        [Header("Steering")]
        [Tooltip("Yaw acceleration (deg/s²) at full rudder and full steerage speed.")]
        [SerializeField] private float rudderTurnAccel = 14f;
        [Tooltip("Speed through the water (m/s) at which the rudder reaches full authority.")]
        [SerializeField] private float steerageSpeed = 3f;

        [Header("Water")]
        [Tooltip("Drag on forward motion (fraction of velocity shed per second).")]
        [SerializeField] private float forwardDrag = 0.25f;
        [Tooltip("Drag on sideways motion. Keep well above forward drag so the ship carves, not slides.")]
        [SerializeField] private float lateralDrag = 1.6f;
        [Tooltip("Drag on yaw rotation.")]
        [SerializeField] private float yawDrag = 0.7f;

        [Header("Anchor")]
        [Tooltip("Extra drag on everything while the anchor is down.")]
        [SerializeField] private float anchorDrag = 3f;
        [Tooltip("How long hauling the anchor back up takes (s). Dropping is instant — the " +
                 "panic brake — but weighing is slow manual work at the bow.")]
        [SerializeField] private float weighSeconds = 5f;

        // Helm state, synced so every client can drive visuals (wheel spin) locally. Sail state
        // lives in the per-mast ShipSailStation SyncVars.
        [SyncVar] private float _rudder;                          // -1..1
        [SyncVar] private bool _anchored;
        [SyncVar] private bool _weighing; // anchor coming up; still holds until fully aweigh

        /// <summary>Current rudder deflection, -1 (hard port) to 1 (hard starboard).</summary>
        public float Rudder => _rudder;

        /// <summary>How many masts currently fly their sails. Valid on server and clients.</summary>
        public int SailLevel
        {
            get
            {
                int n = 0;
                foreach (ShipSailStation s in sailStations)
                    if (s != null && s.Unfurled) n++;
                return n;
            }
        }

        public int MaxSailLevel => sailStations.Length;
        public bool Anchored => _anchored;
        /// <summary>The anchor is being hauled in (still holding until it's fully up).</summary>
        public bool WeighingAnchor => _weighing;
        /// <summary>Signed speed along the bow in m/s. Only meaningful on the server.</summary>
        public float ForwardSpeed => Vector3.Dot(_rb.linearVelocity, transform.forward);
        /// <summary>Speed over the water in m/s regardless of heading. Only meaningful on the server.</summary>
        public float LinearSpeed => _rb.linearVelocity.magnitude;

        [Tooltip("How quickly the hull's height chases the wave surface (1/s). Low = a heavy " +
                 "hull that shoulders through chop; the swell still carries it up and over.")]
        [SerializeField] private float heaveResponse = 2.5f;

        [Header("Tilt (REAL pitch/roll on the hull)")]
        [Tooltip("Physical pitch soft limit (deg). The deck genuinely tilts: cargo slides, masts lean.")]
        [SerializeField] private float maxPitchDeg = 3.5f;
        [Tooltip("Physical roll soft limit (deg). Big enough that slick cargo slides in heavy seas.")]
        [SerializeField] private float maxRollDeg = 9f;
        [Tooltip("Natural frequency (rad/s) of the hull's tilt response to the wave plane.")]
        [SerializeField] private float tiltStiffness = 1.5f;
        [Tooltip("Damping ratio of the tilt response (<1 rings briefly).")]
        [SerializeField] private float tiltDamping = 0.55f;
        [Tooltip("Heel under helm: roll (deg) per (rad/s yaw rate x m/s speed). Sign flips heel direction.")]
        [SerializeField] private float heelFactor = 2.2f;
        [Tooltip("How quickly the hull chases its target attitude (1/s) — the tilt twin of heaveResponse.")]
        [SerializeField] private float tiltResponse = 5f;

        private Rigidbody _rb;
        private ShipFloatView _floatView;      // wave-sample extents live there
        private float _tiltPitch, _tiltRoll;   // oscillator state (deg, unbounded)
        private float _tiltPitchV, _tiltRollV;
        private float _weighDoneAt;       // server: when the running haul brings the anchor up
        private bool _tiltLiveLogged;     // one-shot proof in the console that tilt is physical
        private float _tiltStallSince;    // attitude ignoring the drive since (0 = tracking)
        private bool _tiltStallWarned;
        [SyncVar] private float _planeY;  // the calm-water baseline the heave oscillates around
        private Game.Gameplay.WaterSurface _water;
        private float _nextWaterScan;

        /// <summary>How far the hull currently rides above its calm-water baseline. Valid on
        /// every peer (the baseline is synced; the height comes off the replicated transform).
        /// Visual layers subtract this so they only add what the physics hasn't already done.</summary>
        public float HeaveOffset => transform.position.y - _planeY;

        private void Awake()
        {
            _rb = GetComponent<Rigidbody>();
            _floatView = GetComponent<ShipFloatView>();
            // A genuinely free body: no constraints at all. Height rides the wave field
            // (DriveHeave) and pitch/roll chase the wave plane (DriveTilt) — both through
            // velocities the solver integrates, so the walkable colliders, parented crew
            // and lashed cargo all live on a deck that REALLY moves. Commanding the
            // angular velocity fresh each step is what keeps collisions from winding up
            // uncontrolled spin — the job the old FreezeRotationX/Z lock used to do.
            _rb.constraints = RigidbodyConstraints.None;
            _rb.useGravity = false;
            _rb.linearDamping = 0f;   // drag is modelled explicitly, per-axis, in FixedUpdate
            _rb.angularDamping = 0f;
            _rb.interpolation = RigidbodyInterpolation.Interpolate;
            IgnoreOwnKinematicColliders();
        }

        // The walkable colliders (deck, rails, masts, props) sit on kinematic CHILD bodies so
        // that player contacts can't shove the hull. Those children overlap the root's own hull
        // box by construction — silence the pairs so the ship doesn't fight itself.
        private void IgnoreOwnKinematicColliders()
        {
            Collider[] all = GetComponentsInChildren<Collider>(true);
            foreach (Collider a in all)
            {
                if (a.isTrigger || !a.enabled || !a.gameObject.activeInHierarchy) continue;
                if (a.attachedRigidbody != _rb) continue;
                foreach (Collider b in all)
                {
                    if (b.isTrigger || !b.enabled || !b.gameObject.activeInHierarchy) continue;
                    Rigidbody rb = b.attachedRigidbody;
                    if (rb != null && rb != _rb && rb.isKinematic)
                        Physics.IgnoreCollision(a, b, true);
                }
            }
        }

        public override void OnStartServer() => _planeY = transform.position.y;

        public override void OnStartClient()
        {
            // Remote ships are driven by the NetworkTransform, not local physics.
            if (!isServer) _rb.isKinematic = true;
        }

        [Server] public void SetRudder(float value) => _rudder = Mathf.Clamp(value, -1f, 1f);

        [Server]
        public void SetAnchored(bool anchored)
        {
            _anchored = anchored;
            _weighing = false; // any hard state change ends a haul in progress
        }

        /// <summary>Server: the bow anchor station's toggle. Dropping is instant anywhere —
        /// the panic brake. Weighing is slow manual work: the haul runs for weighSeconds
        /// (pressing again lets the anchor go back down) and the ship stays held until the
        /// anchor is fully up. When a jetty holds the ship it's the mooring line, not the
        /// anchor — release through the jetty (marked manually cast off, so the berth
        /// doesn't instantly re-catch), which is immediate.</summary>
        [Server]
        public void ServerToggleAnchor()
        {
            if (!_anchored)
            {
                SetAnchored(true);
                return;
            }
            foreach (DockMooring dock in FindObjectsByType<DockMooring>(FindObjectsSortMode.None))
                if (dock.MooredShip == this)
                {
                    dock.ServerCastOff();
                    return;
                }
            if (_weighing) _weighing = false; // let go again mid-haul
            else
            {
                _weighing = true;
                _weighDoneAt = Time.time + weighSeconds;
            }
        }

        [ServerCallback]
        private void FixedUpdate()
        {
            // A finished haul frees the ship. (Sails do NOT weigh a dropped anchor — that
            // is deliberate manual work at the bow; only a jetty's mooring line slips by
            // itself when the crew makes sail, handled by DockMooring.)
            if (_anchored && _weighing && Time.time >= _weighDoneAt) SetAnchored(false);

            Vector3 v = _rb.linearVelocity;
            float fwdSpeed = Vector3.Dot(v, transform.forward);

            // Thrust from however many masts fly canvas (the anchor holds the ship regardless).
            if (!_anchored)
            {
                float thrust = sailThrust[Mathf.Clamp(SailLevel, 0, sailThrust.Length - 1)];
                _rb.AddForce(transform.forward * thrust, ForceMode.Acceleration);
            }

            // Rudder authority builds with speed through the water and flips when making sternway.
            float authority = Mathf.Clamp01(Mathf.Abs(fwdSpeed) / Mathf.Max(0.01f, steerageSpeed));
            float sign = fwdSpeed >= 0f ? 1f : -1f;
            _rb.AddTorque(0f, _rudder * rudderTurnAccel * Mathf.Deg2Rad * authority * sign,
                0f, ForceMode.Acceleration);

            // Anisotropic water drag, plus the anchor's contribution on every axis.
            Vector3 fwd = transform.forward * fwdSpeed;
            Vector3 lat = v - fwd;
            float extra = _anchored ? anchorDrag : 0f;
            _rb.AddForce(-fwd * (forwardDrag + extra) - lat * (lateralDrag + extra),
                ForceMode.Acceleration);
            // Yaw only: pitch/roll velocities belong to DriveTilt's chase — damping them
            // here (triply so at anchor) would fight the swell's hold on the hull.
            _rb.AddTorque(0f, -_rb.angularVelocity.y * (yawDrag + extra), 0f,
                ForceMode.Acceleration);

            DriveHeave(v);
            DriveTilt(Time.fixedDeltaTime, fwdSpeed);
        }

        // Buoyant heave: chase the wave field's height under the hull (sampled at a few
        // stations and averaged, so chop shorter than the ship cancels out) with a lagged
        // vertical velocity — the swell carries the whole PHYSICAL ship, colliders, crew
        // and all, up and over. Everyone aboard rides for free via parenting, exactly as
        // they already do for the ship's planar motion; the synced wave clock keeps every
        // peer's sea agreeing with where the server put the hull.
        [Server]
        private void DriveHeave(Vector3 velocity)
        {
            if (_water == null && Time.time >= _nextWaterScan)
            {
                _nextWaterScan = Time.time + 2f;
                _water = FindAnyObjectByType<Game.Gameplay.WaterSurface>();
            }

            float targetY = _planeY;
            if (_water != null)
            {
                Vector3 fwd10 = transform.forward * 10f;
                Vector3 p = _rb.position;
                float mean = 0.25f * (
                    _water.HeightAt(p.x + fwd10.x, p.z + fwd10.z) +
                    _water.HeightAt(p.x - fwd10.x, p.z - fwd10.z) +
                    _water.HeightAt(p.x + transform.right.x * 3f, p.z + transform.right.z * 3f) +
                    _water.HeightAt(p.x - transform.right.x * 3f, p.z - transform.right.z * 3f));
                targetY += mean - _water.SurfaceY;
            }
            // Clamped: if the hull is blocked (beached, resting on something), the drive
            // presses gently instead of building a crushing velocity that friction-pins
            // the ship against whatever is under it.
            float vy = Mathf.Clamp((targetY - _rb.position.y) * heaveResponse, -2.5f, 2.5f);
            _rb.linearVelocity = new Vector3(velocity.x, vy, velocity.z);
        }

        // REAL tilt: the hull rigidbody genuinely pitches and rolls — colliders, parented
        // crew and resting cargo all live on a tilting deck (cargo slides; someday, with
        // true buoyancy forces, a ship can broach and sink). The target attitude comes
        // from the same least-squares wave-plane fit the old visual layer used (5
        // stations x 2 sides so short chop can't alias into inverted tilt), plus heel
        // under helm; a damped oscillator makes waves shoulder the hull rather than
        // glue it to the surface. The body is steered there through ANGULAR VELOCITY —
        // the tilt twin of DriveHeave's vertical chase — never a rotation write, which
        // the solver is free to ignore or judder through; re-commanding the velocity
        // every step is also what stops collisions winding up uncontrolled spin now
        // that the rotation constraints are gone.
        [Server]
        private void DriveTilt(float dt, float fwdSpeed)
        {
            float pitchT = 0f, rollT = 0f;
            float halfLength = _floatView != null ? _floatView.SampleHalfLength : 12f;
            float halfBeam = _floatView != null ? _floatView.SampleHalfBeam : 2.8f;

            if (_water != null)
            {
                const int stations = 5;
                float zExtent = halfLength * 0.55f;
                float sumZH = 0f, sumXH = 0f, sumZZ = 0f, sumXX = 0f;
                for (int zi = 0; zi < stations; zi++)
                {
                    float z = Mathf.Lerp(-zExtent, zExtent, zi / (stations - 1f));
                    for (int side = -1; side <= 1; side += 2)
                    {
                        float x = halfBeam * side;
                        Vector3 p = transform.TransformPoint(x, 0f, z);
                        float h = _water.HeightAt(p.x, p.z) - _water.SurfaceY;
                        sumZH += z * h; sumZZ += z * z;
                        sumXH += x * h; sumXX += x * x;
                    }
                }
                pitchT = -Mathf.Atan(sumZH / sumZZ) * Mathf.Rad2Deg; // stern high = bow down
                rollT = Mathf.Atan(sumXH / sumXX) * Mathf.Rad2Deg;   // starboard high = roll to port
            }

            // Heel under helm: yaw rate x speed leans the hull through a turn.
            rollT += heelFactor * _rb.angularVelocity.y * fwdSpeed;

            float w2 = tiltStiffness * tiltStiffness;
            float d = 2f * tiltDamping * tiltStiffness;
            _tiltPitchV += ((pitchT - _tiltPitch) * w2 - d * _tiltPitchV) * dt;
            _tiltRollV += ((rollT - _tiltRoll) * w2 - d * _tiltRollV) * dt;
            _tiltPitch += _tiltPitchV * dt;
            _tiltRoll += _tiltRollV * dt;

            float targetPitch = SoftLimit(_tiltPitch, maxPitchDeg);
            float targetRoll = SoftLimit(_tiltRoll, maxRollDeg);

            // X/Z angular velocity chases the target attitude; yaw (Y) stays whatever
            // the rudder and drag made it. Clamped so a big error (spawn, teleport)
            // rights the ship briskly, not violently.
            Vector3 e = _rb.rotation.eulerAngles;
            float pitchErr = Mathf.DeltaAngle(Mathf.DeltaAngle(0f, e.x), targetPitch);
            float rollErr = Mathf.DeltaAngle(Mathf.DeltaAngle(0f, e.z), targetRoll);
            Vector3 localAV = Quaternion.Inverse(_rb.rotation) * _rb.angularVelocity;
            localAV.x = Mathf.Clamp(pitchErr * tiltResponse, -40f, 40f) * Mathf.Deg2Rad;
            localAV.z = Mathf.Clamp(rollErr * tiltResponse, -40f, 40f) * Mathf.Deg2Rad;
            _rb.angularVelocity = _rb.rotation * localAV;

            // Insurance against flying blind either way: log once when the hull's REAL
            // attitude first comes alive, and warn if it persistently ignores the drive
            // (which would look exactly like "the tilt is still only visual").
            float actualPitch = Mathf.DeltaAngle(0f, e.x);
            float actualRoll = Mathf.DeltaAngle(0f, e.z);
            float actual = Mathf.Abs(actualPitch) + Mathf.Abs(actualRoll);
            if (!_tiltLiveLogged && actual > 1.5f)
            {
                _tiltLiveLogged = true;
                Debug.Log($"[ShipController] Physical tilt live: pitch {actualPitch:F1}°, roll {actualRoll:F1}°.");
            }
            float want = Mathf.Abs(targetPitch) + Mathf.Abs(targetRoll);
            if (want > 1.5f && actual < 0.25f * want)
            {
                if (_tiltStallSince <= 0f) _tiltStallSince = Time.time;
                else if (!_tiltStallWarned && Time.time - _tiltStallSince > 4f)
                {
                    _tiltStallWarned = true;
                    Debug.LogWarning($"[ShipController] Hull attitude is NOT following the tilt drive " +
                        $"(wants pitch {targetPitch:F1}° roll {targetRoll:F1}°, sitting at " +
                        $"{actualPitch:F1}°/{actualRoll:F1}°). Something is zeroing the angular velocity.", this);
                }
            }
            else _tiltStallSince = 0f;
        }

        private static float SoftLimit(float x, float max) =>
            max <= 0f ? 0f : max * (float)System.Math.Tanh(x / max);

    }
}
